version: "3.8"

services:
  test_signer:
    image: golang:1.21.6-alpine3.19
    depends_on:
      - test_signer_db
    ports:
      - "80:8080"
    environment:
      DB_HOST: test_signer_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: test_signer


  test_signer_db:
    image: postgres:13-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_signer
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
