version: "3.8"

services:
  test_signer:
    image: golang:1.21.6-alpine3.19
    ports:
      - "80:8080"
  db:
    image: postgres:13-bullseye
    environment:
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
      - POSTGRES_DB: test_signer
    volumes:
      db_data:/var/lib/postgresql/data

volumes:
  db_data:
