openapi: '3.0.0'
info:
  title: Test Signer API
  version: 1.0.0
paths:
  /api/v1/tests/{id}/answers:
    post:
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1
          description: Id of a test
          required: true
      requestBody:
        description: list of question-answer pairs for given test
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TestAnswer'

      responses:
        '200':
          description: answers accepted and signed
components:
  schemas:
    TestAnswer:
      type: object
      properties:
        questionId:
          type: integer
          minimum: 1
        answers:
          type: array
          items:
            type: integer


